### ISSUE TITLE
Jenkins isn't showing the Full UI in "Manage Jenkins" -> "Configure System"

### ISSUE THREAD

**Issue by pcarney8** [rht-labs/s2i-config-jenkins#17]
Something is malformed in the UI, so it prevents the top half and bottom half from rendering. Including having no "save" button in the UI. 

The `config.xml` is complete and well-formed in the container though.

```
Uncaught TypeError: Cannot read property 'firstChild' of undefined
    at registerValidator (hudson-behavior.js:424)
    at Array.forEach (<anonymous>)
    at behavior.js:111
    at Array.forEach (<anonymous>)
    at behavior.js:107
    at Array.forEach (<anonymous>)
    at Object.applySubtree (behavior.js:93)
    at select.js:269
```
and a warning for:
```
configure:1 [DOM] Found 2 elements with non-unique id #svn.remote.loc: (More info: https://goo.gl/9p2vKq) <input checkdependson=​"remote" onchange=​"{ /​* workaround for JENKINS-19124 */​             var self=this.targetElement ? this.targetElement :​ this;​             var r=findNextFormItem(self,'credentialsId')​;​             r.onchange(r)​;​             if (self===document.getElementById('svn.remote.loc')​)​{                 r=findNextFormItem(self,'excludedRevprop')​;​                 r.onchange(r)​;​             }​             self=null;​             r=null;​     }​" id=​"svn.remote.loc" checkurl=​"/​descriptorByName/​hudson.scm.SubversionSCM$ModuleLocation/​checkRemote" name=​"_.remote" type=​"text" class=​"setting-input validated  " value>​ <input checkdependson=​"remote" onchange=​"{ /​* workaround for JENKINS-19124 */​             var self=this.targetElement ? this.targetElement :​ this;​             var r=findNextFormItem(self,'credentialsId')​;​             r.onchange(r)​;​             if (self===document.getElementById('svn.remote.loc')​)​{                 r=findNextFormItem(self,'excludedRevprop')​;​                 r.onchange(r)​;​             }​             self=null;​             r=null;​     }​" id=​"svn.remote.loc" checkurl=​"/​descriptorByName/​hudson.scm.SubversionSCM$ModuleLocation/​checkRemote" name=​"_.remote" type=​"text" class=​"setting-input validated  " value>​
```

**Comment by mcanoy** [comment]
i see this when using the master branch after upgraded from tag v1.3. When I disable the plugin `nexus-jenkins-plugin:3.7.20190823-091836.9f85050` the save button returns. Still lots of errors in the logs

```bash
WARNING: Caught exception evaluating: h.filterDescriptors(it,attrs.descriptors) in /configure. Reason: java.lang.NullPointerException: Descriptor list is null for context 'class hudson.model.Hudson' in thread 'Handling GET /configure from 10.9.55.81 : qtp5883478-15 Jenkins/configure.jelly GlobalLibraries/config.jelly LibraryConfiguration/config.jelly SCMRetriever/DescriptorImpl/config.jelly MultiSCM/DescriptorImpl/config.jelly'
java.lang.NullPointerException: Descriptor list is null for context 'class hudson.model.Hudson' in thread 'Handling GET /configure from 10.9.55.81 : qtp5883478-15 Jenkins/configure.jelly GlobalLibraries/config.jelly LibraryConfiguration/config.jelly SCMRetriever/DescriptorImpl/config.jelly MultiSCM/DescriptorImpl/config.jelly'
	at hudson.model.DescriptorVisibilityFilter.apply(DescriptorVisibilityFilter.java:73)
	at hudson.Functions.filterDescriptors(Functions.java:1876)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)

--


```
